### ISSUE TITLE
Aparapi and Ray Casting (Ray Tracing)

### ISSUE THREAD

**Issue by macroing** [aparapi/aparapi#11]
Hello!

I've used Aparapi for a while now and I really like it. The project I've been working on is an open source realtime Ray Caster (Ray Tracer).

But now I'm interested in hearing your input on Aparapi- / OpenCL specific optimizations for a project like this. Would it be a good idea to use the local and / or global buffer annotations? Or do you have any other ideas?

In case you're interested in the project, you can find it here: https://github.com/macroing/OpenRC

**Comment by SubaruWRC** [comment]
I hate to say this, but it really depends on your computation/workload. Have you looked at any of the samples/examples on Github to see if they match your use cases?


On September 17, 2015 2:23:18 AM PDT, macroing <notifications@github.com> wrote:
>Hello!
>
>I've used Aparapi for a while now and I really like it. The project
>I've been working on is an open source realtime Ray Caster (Ray
>Tracer).
>
>But now I'm interested in hearing your input on Aparapi- / OpenCL
>specific optimizations for a project like this. Would it be a good idea
>to use the local and / or global buffer annotations? Or do you have any
>other ideas?
>
>In case you're interested in the project, you can find it here:
>https://github.com/macroing/OpenRC
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/aparapi/aparapi/issues/11

-- 
Sent from my mobile device. Please excuse any typos or autocorrect mistakes.

**Comment by macroing** [comment]
Okay I see. Yes, I looked at some of the examples. I even based the initial code on the approach used by the Fractal example.

What concerns the computation or workload, then I guess it's quite heavy. The more rays the Ray Tracer "fires" per pixel, the more workload per pixel. Then there's also quite a few pixels to process.

**Comment by freemo** [comment]
This issue was moved to Syncleus/aparapi#5
