### ISSUE TITLE
Issue with ProfileInfo timers? 

### ISSUE THREAD

**Issue by jjfumero** [aparapi/aparapi#24]
I am interested in measuring the timers for copy in, execution and copy out of OpenCL code generated by Aparapi. If I do this on AMD GPU, the data transfer is 0 .

```
 private static class SaxpyKernel extends Kernel {
        private float alpha = 0.4f;
        private float[] x;
        private float[] y;
        private float[] z;

        public SaxpyKernel() {
        }

        public float[] getResult() {
            return this.z;
        }

        public void setArrays(float[] x, float[] y) {
            this.x = x;
            this.y = y;
            this.z = new float[x.length];
        }       

        @Override
        public void run() {
            int idx = getGlobalId();
            z[idx] = alpha * x[idx] + y[idx];
        }
}
```

If I print the timers for data transfer + kernel execution like this:

```
               Range range = Range.create(size);
        SaxpyKernel kernel = new SaxpyKernel();
        kernel.setExecutionMode(Kernel.EXECUTION_MODE.GPU);
               kernel.setArrays(a, b);

        for (int i = 0; i < ITERATIONS; i++) {      
            kernel.execute(range);
            List<ProfileInfo> profileInfo = kernel.getProfileInfo();
            for (ProfileInfo p : profileInfo) {             
                System.out.println(" " + p.getType()  + " : " + ((p.getEnd() - p.getStart())) + " (ns)");
            }
        }
```

I get these timers:

 W : 0 (ns)
 X : 6492297 (ns)
 R : 0 (ns)

This happens ONLY on AMD GPU (AMD Radeon R9). If I use either Intel CPU (with Intel driver) or NVIDIA GPU I get these timers > 0 ns.

**Comment by jjfumero** [comment]
Hi, 
  I investigated this case. Aparapi uses CL_MEM_USE_HOST_PTR when the OpenCL buffer is created. 

[Link to source](https://github.com/aparapi/aparapi/blob/6319738b58b1567cd36640610f4d8181a31743c4/com.amd.aparapi.jni/src/cpp/runKernel/Aparapi.cpp#L350) 

Part of the source code: 
```
   cl_uint mask = CL_MEM_USE_HOST_PTR;
   if (arg->isReadByKernel() && arg->isMutableByKernel()) mask |= CL_MEM_READ_WRITE;
   else if (arg->isReadByKernel() && !arg->isMutableByKernel()) mask |= CL_MEM_READ_ONLY;
   else if (arg->isMutableByKernel()) mask |= CL_MEM_WRITE_ONLY;
   arg->arrayBuffer->memMask = mask;

   if (config->isVerbose()) {
      strcpy(arg->arrayBuffer->memSpec,"CL_MEM_USE_HOST_PTR");
      if (mask & CL_MEM_READ_WRITE) strcat(arg->arrayBuffer->memSpec,"|CL_MEM_READ_WRITE");
      if (mask & CL_MEM_READ_ONLY) strcat(arg->arrayBuffer->memSpec,"|CL_MEM_READ_ONLY");
      if (mask & CL_MEM_WRITE_ONLY) strcat(arg->arrayBuffer->memSpec,"|CL_MEM_WRITE_ONLY");

      fprintf(stderr, "%s %d clCreateBuffer(context, %s, size=%08lx bytes, address=%p, &status)\n", arg->name, 
            argIdx, arg->arrayBuffer->memSpec, (unsigned long)arg->arrayBuffer->lengthInBytes, arg->arrayBuffer->addr);
   }

```

The [OpenCL standard](https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clCreateBuffer.html) specifies: 

> OpenCL implementations are allowed to cache the buffer contents pointed to by host_ptr in device memory. This cached copy can be used when kernels are executed on a device. 

Which is actually what is happening. I did a sanity check in pure OpenCL C++ (saxpy on this AMD GPU with this flag enabled, and I get the same result, 0 ns for copy in and copy out). The kernel time includes the data transfer + kernel execution. 

If I run this [benchmark ](https://bitbucket.org/juanfumero/opencl-samples/src/eac38234f97e06b7be4b5d9d675d21903afc11b5/c++/saxpy/saxpy.cpp?at=default&fileviewer=file-view-default)on AMD GPU I get the same result that Aparapi. Line [161](https://bitbucket.org/juanfumero/opencl-samples/src/eac38234f97e06b7be4b5d9d675d21903afc11b5/c++/saxpy/saxpy.cpp?at=default&fileviewer=file-view-default#saxpy.cpp-161) is the function that creates the buffers on the GPU.

Execution with CL_MEM_USE_HOST_PTR:

```
$  ./saxpy 
OpenCL Saxpy 
Size = 67108864
... 
Median KernelTime: 5.2658e+07 (ns)
Median CopyInTime: 0 (ns)
Median CopyOutTime: 0 (ns)
Median TotalTime: 5.29082e+07 (ns)
```

Same application without CL_MEM_USE_HOST_PTR:

```
$ ./saxpy 
OpenCL Saxpy 
Size = 67108864
...
Median KernelTime: 4.27496e+06 (ns)
Median CopyInTime: 6.35572e+07 (ns)
Median CopyOutTime: 3.15384e+07 (ns)
Median TotalTime: 1.09869e+08 (ns)

```

### Conclusion

The is nothing wrong with Aparapi. It is just the driver implementer is free to do the caching when the kernel is going to be executed. The only thing is, when Aparapi reports the timers for copy in, execution and copy back, the kernel time includes the data transfer.

**Comment by grfrost** [comment]
Hey.  Thanks for doing this work and reporting back to the community.

I must confess I put this code together fairly late in the project (piggy
backing on some great work from Eric) and have always felt a bit suspect
about it.

Again thanks for following up.

Gary

**Comment by freemo** [comment]
This issue was moved to Syncleus/aparapi#9

**Comment by rlamothe** [comment]
@jjfumero Awesome, thank you! I will take note of this to add to the official documentation.
