### ISSUE TITLE
Will you be supporting SPIR-V?

### ISSUE THREAD

**Issue by volkertb** [aparapi/aparapi#28]
Since SPIR-V has been announced and blessed by the Khronos Group as the new universal intermediate representation format for both shader and kernel code, for use not only in Vulkan, but also in OpenCL going forward, I was wondering what your plans are for Aparapi to support compiling the Java kernel code to SPIR-V in addition to the current functionality?

( For those of you reading this who are not yet familiar with SPIR-V, see https://www.khronos.org/spir )

At any rate, thanks for this fun and useful library! I'm already having a lot of fun playing with Aparapi in my spare time project. Keep up the good work. :-)

**Comment by freemo** [comment]
This issue was moved to Syncleus/aparapi#12

**Comment by rlamothe** [comment]
We'd love to do so! Any pull requests supporting this feature will be quickly evaluated. A long-term dream for Aparapi would be to create both OpenCL and CUDA :)
