### ISSUE TITLE
Definition of a constant

### ISSUE THREAD

**Issue by Oyatsumi** [aparapi/aparapi#33]
Where is the definition of com_amd_aparapi_internal_jni_KernelRunnerJNI_JNI_FLAG_USE_ACC
located in the source code?

It has not been defined and I cant compile the source code.

Thank you in advance.

**Comment by grfrost** [comment]
javah will create a header for this during the build.

So if you use javah on class com.amd.aparapi.internal.jni.KernelRunnerJNI
class file this will create a header file which contains the #defines for
these constants as well as as the function prototypes for JNI linkage with
the JVM.

Gary

**Comment by freemo** [comment]
This issue was moved to Syncleus/aparapi#17

**Comment by rlamothe** [comment]
@Oyatsumi Were you able to build the native code on your platform? I am able to build the native code without issue on OS X, so I will close this issue unless you say otherwise. Thanks!
