### ISSUE TITLE
A kernel cannot be recompiled after it is disposed

### ISSUE THREAD

**Issue by sharpTrick** [aparapi/aparapi#34]
Any time a kernel is disposed with the intent of recompiling results in attempts to fall back to next device. This bug specifically effects this code in [KernelRunner.java L1348](https://github.com/aparapi/aparapi/blob/master/com.amd.aparapi/src/java/com/amd/aparapi/internal/kernel/KernelRunner.java#L1348)

I believe that it is specifically due to the persistence of the `seenBinaryKeys` set after disposing of the `jniContextHandle` in [KernelRunner.java L190](https://github.com/aparapi/aparapi/blob/master/com.amd.aparapi/src/java/com/amd/aparapi/internal/kernel/KernelRunner.java#L190). 

I believe that by simply clearing the `seenBinaryKeys` set upon disposal will resolve this issue.

**Comment by freemo** [comment]
This issue was moved to Syncleus/aparapi#18

**Comment by rlamothe** [comment]
Your KernelRunner fix was committed, but the Maven/Gradle refactoring is still on-going.
