### ISSUE TITLE
Use of Aparapi libraries in Apache projects

### ISSUE THREAD

**Issue by edwardyoon** [aparapi/aparapi#37]
Hi,

My name is edward, a member of Apache Software Foundation. I recently considering use of Aparapi in my (Java-based) open source projects (Apache Hama [1] and HORN [2]) but heard that Aparapi license is not suitable for inclusion in Apache products [3]. Can you allow us to include aparapi binary files, or give me some feedbacks?

Thanks.

1. https://hama.apache.org/
2. https://github.com/apache/incubator-horn
3. https://issues.apache.org/jira/browse/LEGAL-268

**Comment by grfrost** [comment]
Hey Edward

AMD chose the modified BSD license when they contributed the initial code.
I no longer work for AMD.

It was my understanding that Apache and BSD are OK together (I am not a
lawyer!)

http://www.apache.org/legal/resolved.html

If not I am not sure how hard it would be to dual license under apache and
BSD.  Not too hard I expect. But it would require AMD (at least) but
probably all contributors to  agree.

But from my reading of the apache link above BSD and Apache are compatible.

Gary

**Comment by edwardyoon** [comment]
@grfrost Thanks, gary. 

ASF legal team advised me as follow:

> Closing. This license is not suitable for inclusion in Apache products.
> We advise you contact AMD to seek a license change to one that would fit with the OSI definition.
> Please reopen/contact on license-discuss if you would like to discuss further.

Can you please let me know the contact AMD?

**Comment by grfrost** [comment]
Hi

So I don't have a name par se.   I would suggest asking on the forums at
'AMD developer central' to find out who to ask.

https://community.amd.com/community/devgurus

You may have to register to ask a question.

Sorry I can't be more helpful.  Even though I wrote probably close to 90%
of the code, AMD (as my employer) owns it and they essentially control the
licensing going forward.

Gary

**Comment by edwardyoon** [comment]
Thanks, I'll also ask there. Close.
