### ISSUE TITLE
Aparapi can't find OpenCL

### ISSUE THREAD

**Issue by thejar** [aparapi/aparapi#4]
I have been having some trouble getting aparapi to work on my desktop.
I'm running Windows 7 64 bit with an AMD graphics card and all appropriate drivers installed.
output from clinfo: http://pastebin.com/fA0Pke8Y

from latest release on code google (https://code.google.com/p/aparapi/downloads/list)
output from info sample: http://pastebin.com/wiYGEcGP
output from add sample: http://pastebin.com/GEXMR70r

from latest release on Github (https://github.com/aparapi/aparapi/releases)
output from info sample: http://pastebin.com/mbQWMybd
output from add sample: http://pastebin.com/KeWp6XnM

The aparapi.jar and opencl.dll files are both in locations in the windows path.
I can only imagine that I don't have something set up correctly, but would appreciate any help getting this to work.
Thanks,
Jeff

![geeks3d_gpu_caps_viewer_gpu](https://cloud.githubusercontent.com/assets/7593939/5731960/5bf61f28-9b58-11e4-9f8e-b04c68da2649.jpg)
![geeks3d_gpu_caps_viewer_opencl](https://cloud.githubusercontent.com/assets/7593939/5731959/5bf20488-9b58-11e4-877e-91462e3121d1.jpg)

**Comment by grfrost** [comment]
Looks like our emails crossed.  So you are using OpenCL 1.2.  That should
be fine.

The next thing I would try is running your Aparapi app with

-Dcom.amd.aparapi.enableVerboseJNI=true

It should dump out a bunch of logging messages, including info on
whether it located OpenCL libs.

Gary

**Comment by freemo** [comment]
This issue was moved to Syncleus/aparapi#3

**Comment by rlamothe** [comment]
Jeff,

Any update on this issue? Were you able to get Aparapi work and/or OpenCL libraries loaded?

**Comment by thejar** [comment]
I never got it to work with the AMD card, but it worked with an NVIDIA card with minimal difficulty.
