### ISSUE TITLE
error: function "getClass" declared implicitly

### ISSUE THREAD

**Issue by ppeter5** [aparapi/aparapi#40]
I am running with JDK 1.8_101. 
Here the details, this is the Aparapi Kernel:

    public static class TrainKernel extends Kernel {
        private final int maps[];
        private final int vectors[];
        private final int tmp[];
        private final int mapSize, vectorSize, vectorsCount, epoch, bSize = 64;

        TrainKernel(int[][] vectors, int[][] maps, int epoch) {
            this.epoch=epoch;
            vectorSize=vectors[0].length;
            vectorsCount=vectors.length;
            this.vectors=new int[vectorsCount*vectorSize];
            int count=0;
            for (int i = 0; i < vectorsCount; i++) {
                for (int j = 0; j < vectorSize; j++, count++) {
                    this.vectors[count] = vectors[i][j];
                }
            }
            mapSize = maps[0].length;
            this.maps =new int[maps.length* mapSize];
            count=0;
            for (int i = 0; i < maps.length; i++) {
                for (int j = 0; j < mapSize; j++, count++) {
                    this.maps[count] = maps[i][j];
                }
            }
            tmp=new int[maps.length * mapSize * bSize];
        }

        @Override
        public void run() { 
            final int mSize= mapSize;
            final int bSize = this.bSize;
            final int mStart=mSize*getGlobalId();
            final int tStart=mStart*bSize;
            final int vectorsLength=vectors.length;
            final int vSize=vectorSize;
            final int count = vSize - mSize + 1;
            final int tLength=mSize * bSize;
            for (int e = 0; e < epoch; e++) {
                for (int i = 0; i < tLength; i++) {
                    tmp[tStart+i]=0;
                }
                for (int vStart = 0; vStart < vectorsLength; vStart=vStart+vSize) {
                    int maximum = 0;
                    int maxIndex = 0;
                    for (int i = 0; i < count; i++) {
                        int sum = 0;
                        for (int j = 0; j < mSize; j++) {
                            sum = sum + (vectors[vStart+i + j] & maps[mStart+j]);
                        }
                        if (maximum < sum) {
                            maximum = sum;
                            maxIndex = i;
                        }
                    }
                    for (int j = 0; j < mSize; j++) {
                        tmp[tStart+j*bSize+vectors[vStart + maxIndex + j] ^ maps[mStart + j]]++;
                    }
                }
                int sum = 0;
                for (int i = 0; i < mSize; i++) {
                    int maximum = 0;
                    int maxIndex = 0;
                    for (int j = 0; j < bSize; j++) {
                        if (maximum < tmp[tStart+i*bSize+j]) {
                            maximum = tmp[tStart+i*bSize+j];
                            maxIndex = j;
                        }
                    }
                    sum = sum + maxIndex;
                    maps[mStart+i] = maps[mStart+i] | maxIndex;
                }
                if (sum == 0) {
                    return;
                }
            }
        }
    }

This is the kernel Aparapi generates:

typedef struct This_s{
   int mapSize;
   __global int *vectors;
   int vectors__javaArrayLength0;
   int vectors__javaArrayDimension0;
   int vectorSize;
   int epoch;
   __global int *tmp;
   __global int *maps;
   int passid;
}This;
int get_pass_id(This *this){
   return this->passid;
}
__kernel void run(
   int mapSize, 
   __global int *vectors, 
   int vectors__javaArrayLength0, 
   int vectors__javaArrayDimension0, 
   int vectorSize, 
   int epoch, 
   __global int *tmp, 
   __global int *maps, 
   int passid
){
   This thisStruct;
   This* this=&thisStruct;
   this->mapSize = mapSize;
   this->vectors = vectors;
   this->vectors__javaArrayLength0 = vectors__javaArrayLength0;
   this->vectors__javaArrayDimension0 = vectors__javaArrayDimension0;
   this->vectorSize = vectorSize;
   this->epoch = epoch;
   this->tmp = tmp;
   this->maps = maps;
   this->passid = passid;
   {
      int mSize = this->mapSize;
      getClass();
      int bSize = 64;
      int mStart = mSize * get_global_id(0);
      int tStart = mStart * bSize;
      int vectorsLength = this->vectors__javaArrayLength0;
      int vSize = this->vectorSize;
      int count = (vSize - mSize) + 1;
      int tLength = mSize * bSize;
      for (int e = 0; e<this->epoch; e++){
         for (int i = 0; i<tLength; i++){
            this->tmp[tStart + i]  = 0;
         }
         for (int vStart = 0; vStart<vectorsLength; vStart = vStart + vSize){
            int maximum = 0;
            int maxIndex = 0;
            for (int i = 0; i<count; i++){
               int sum = 0;
               for (int j = 0; j<mSize; j++){
                  sum = sum + (this->vectors[((vStart + i) + j)] & this->maps[(mStart + j)]);
               }
               if (maximum<sum){
                  maximum = sum;
                  maxIndex = i;
               }
            }
            for (int j = 0; j<mSize; j++){
               this->tmp[((tStart + (j * bSize)) + this->vectors[((vStart + maxIndex) + j)]) ^ this->maps[(mStart + j)]]  = this->tmp[((tStart + (j * bSize)) + this->vectors[((vStart + maxIndex) + j)]) ^ this->maps[(mStart + j)]] + 1;
            }
         }
         int sum = 0;
         for (int i = 0; i<mSize; i++){
            {
               int maximum = 0;
               int maxIndex = 0;
               for (int j = 0; j<bSize; j++){
                  if (maximum<this->tmp[((tStart + (i * bSize)) + j)]){
                     maximum = this->tmp[((tStart + (i * bSize)) + j)];
                     maxIndex = j;
                  }
               }
               sum = sum + maxIndex;
               this->maps[mStart + i]  = this->maps[(mStart + i)] | maxIndex;
            }
         }
         if (sum==0){
            return;
         }
      }
      return;
   }
}

There is an error:

nov 20, 2016 4:00:08 PM com.amd.aparapi.internal.kernel.KernelRunner warnFallBackAndExecute
WARNING: Reverting to Java Thread Pool (JTP) for class Layer$TrainKernel: OpenCL compile failed

clBuildProgram failed
************************************************
"C:\TEMP\OCL4704T1.cl", line 39: error: function "getClass" declared implicitly
        getClass();
        ^

**Comment by grfrost** [comment]
Hey Peter

That is weird.

It looks like the 'this.bSize' in your code  is causing this.

 final int bSize = this.bSize;

My guess is that if you remove 'this' it will work.

BTW If these fields are final, aparapi should be able to use them
directly. So I am not sure why you are copying from field final ints
to kernel final ints.

Thanks for posting code and generated code.

Gary

**Comment by freemo** [comment]
This issue was moved to Syncleus/aparapi#20

**Comment by rlamothe** [comment]
@ppeter5 Gary is correct. I changed your code to the following and the kernel executes in GPU mode without exception. Closing for now unless you believe this issue should be re-opened. Thanks!

`public static class TrainKernel extends Kernel {
		private final int maps[];
		private final int vectors[];
		private final int tmp[];
		private final int mapSize, vectorSize, vectorsCount, epoch, bSize = 64;

		TrainKernel(int[][] vectors, int[][] maps, int epoch) {
			this.epoch = epoch;
			vectorSize = vectors[0].length;
			vectorsCount = vectors.length;
			this.vectors = new int[vectorsCount * vectorSize];
			int count = 0;
			for (int i = 0; i < vectorsCount; i++) {
				for (int j = 0; j < vectorSize; j++, count++) {
					this.vectors[count] = vectors[i][j];
				}
			}
			mapSize = maps[0].length;
			this.maps = new int[maps.length * mapSize];
			count = 0;
			for (int i = 0; i < maps.length; i++) {
				for (int j = 0; j < mapSize; j++, count++) {
					this.maps[count] = maps[i][j];
				}
			}
			tmp = new int[maps.length * mapSize * bSize];
		}

		@Override
		public void run() {
			final int mStart = mapSize * getGlobalId();
			final int tStart = mStart * bSize;
			final int vectorsLength = vectors.length;
			final int count = vectorSize - mapSize + 1;
			final int tLength = mapSize * bSize;
			
			for (int e = 0; e < epoch; e++) {
				for (int i = 0; i < tLength; i++) {
					tmp[tStart + i] = 0;
				}
				
				for (int vStart = 0; vStart < vectorsLength; vStart = vStart + vectorSize) {
					int maximum = 0;
					int maxIndex = 0;
					for (int i = 0; i < count; i++) {
						int sum = 0;
						for (int j = 0; j < mapSize; j++) {
							sum = sum + (vectors[vStart + i + j] & maps[mStart + j]);
						}
						if (maximum < sum) {
							maximum = sum;
							maxIndex = i;
						}
					}
					for (int j = 0; j < mapSize; j++) {
						tmp[tStart + j * bSize + vectors[vStart + maxIndex + j] ^ maps[mStart + j]]++;
					}
				}
				int sum = 0;
				for (int i = 0; i < mapSize; i++) {
					int maximum = 0;
					int maxIndex = 0;
					for (int j = 0; j < bSize; j++) {
						if (maximum < tmp[tStart + i * bSize + j]) {
							maximum = tmp[tStart + i * bSize + j];
							maxIndex = j;
						}
					}
					sum = sum + maxIndex;
					maps[mStart + i] = maps[mStart + i] | maxIndex;
				}
				if (sum == 0) {
					return;
				}
			}
		}
	}`
