### ISSUE TITLE
 Error in KernelProfile, no currentDevice (synchronization error? when trying to execute using CPU

### ISSUE THREAD

**Issue by jedld** [aparapi/aparapi#49]
I'm trying to do a simple test unfortunately, trying to get it to work with GPU or CPU results in:

SEVERE: Error in KernelProfile, no currentDevice (synchronization error?

The only time it works is when using JTP, using the default auto results in nothing getting executed.

```
static class TestKernel extends Kernel {
		final float inA[] = new float[] { 1.0f, 2.0f };
		final float inB[] = new float[] { 2.0f, 3.0f };
		final float result[] = new float[inA.length];

		@Override
		public void run() {
			int i = getGlobalId();
			result[i] = inA[i] + inB[i];
		}

		public float[] getResult() {
			return result;
		}
	}

	private static void aparapi() {
		try {
			NativeLoader.load();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		TestKernel kernel = new TestKernel();

		Range range = Range.create(2);
		kernel.setExecutionMode(Kernel.EXECUTION_MODE.CPU);
		kernel.execute(range);

//		OutputUtils.print(kernel.getResult());
	}

```

**Comment by rlamothe** [comment]
Was Aparapi built from source?

**Comment by jedld** [comment]
no it was downloaded as a maven dependency - version 1.4.1

**Comment by grfrost** [comment]
Do you know that your OpenCL runtime is actually working? and configured
correctly?

Can you run clinfo?

Gary

**Comment by jedld** [comment]
I finally got it. it turns out I needed to reinstall opencl. Thanks for your help!

**Comment by carstenhag** [comment]
Getting this error too on win10x64, R9 290, AMD 3.0SDK, seemingly after updating to Radeon 18.2.1 :/

```
Feb 03, 2018 2:13:35 PM com.aparapi.internal.kernel.KernelProfile onEvent
SCHWERWIEGEND: Error in KernelProfile, no currentDevice (synchronization error?
Feb 03, 2018 2:13:35 PM com.aparapi.internal.kernel.KernelProfile onEvent
SCHWERWIEGEND: Error in KernelProfile, no currentDevice (synchronization error?
Exception in thread "main" java.lang.NullPointerException
	at com.aparapi.internal.kernel.KernelProfile.onEvent(KernelProfile.java:90)
	at com.aparapi.internal.kernel.KernelRunner.executeInternalInner(KernelRunner.java:1539)
	at com.aparapi.internal.kernel.KernelRunner.executeInternalOuter(KernelRunner.java:1180)
	at com.aparapi.internal.kernel.KernelRunner.execute(KernelRunner.java:1170)
	at com.aparapi.Kernel.execute(Kernel.java:2473)
	at com.aparapi.Kernel.execute(Kernel.java:2430)
	at com.aparapi.Kernel.execute(Kernel.java:2405)
	at PrimesWithZeroesReplaced.main(PrimesWithZeroesReplaced.java:115)
```

`clinfo` returns that I've got a CPU and a GPU platform (the 290). It is available too.

**Comment by rlamothe** [comment]
Hello, have you built the Github code from the latest source?

**Comment by carstenhag** [comment]
I think so, yes. I was able to build aparapi and aparapi-jni, but not
aparapi-native.

I took the 2014 dll release from the amd repo.

Am 03.02.2018 16:18 schrieb "Ryan LaMothe" <notifications@github.com>:

**Comment by grfrost** [comment]
Is it possible that the OpenCL version # has bumped?

This code was always brittle. At present we only expect 1.1 1.2 and 2.0
versions.

https://github.com/aparapi/aparapi/blob/master/com.amd.aparapi.jni/src/cpp/invoke/OpenCLJNI.cpp#L444

Do we know what version of OpenCL is reported by the driver?

Gary

**Comment by carstenhag** [comment]
Here is the output of `clinfo`: [clinfo.txt](https://github.com/aparapi/aparapi/files/1691996/clinfo.txt)

```
Number of platforms:				 2
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 2.1 AMD-APP (2527.8)
  Platform Name:				 AMD Accelerated Parallel Processing
  Platform Vendor:				 Advanced Micro Devices, Inc.
  Platform Extensions:				 cl_khr_icd cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_amd_event_callback cl_amd_offline_devices 
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 2.1 AMD-APP (2527.8)
  Platform Name:				 AMD Accelerated Parallel Processing
  Platform Vendor:				 Advanced Micro Devices, Inc.
  Platform Extensions:				 cl_khr_icd cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_amd_event_callback cl_amd_offline_devices 

[...]

  Platform Name:				 AMD Accelerated Parallel Processing
Number of devices:				 2
  Device Type:					 CL_DEVICE_TYPE_GPU
  Vendor ID:					 1002h
  Board name:					 AMD Radeon R9 200 Series
[...]
 Device OpenCL C version:			 OpenCL C 2.0 
  Driver version:				 2527.8
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 2.0 AMD-APP (2527.8)
```

Maybe it got updated to 2.1?

**Comment by carstenhag** [comment]
@rlamothe actually, I am not sure if I have built github.com/aparapi/aparapi. I thought your comment was on the Syncleus/aparapi repo.

**Comment by grfrost** [comment]
Yeah the code (written in the days of yore ;) ) looks like this (and even
has a misleading comment)

// fix this so OpenCL 1.3 or higher will not break!
if ( !strncmp(platformVersionName, "OpenCL 1.2", 10)
|| !strncmp(platformVersionName, "OpenCL 1.1", 10)
|| !strncmp(platformVersionName, "OpenCL 2.0", 10)
#ifdef __APPLE__
|| !strncmp(platformVersionName, "OpenCL 1.0", 10)
#endif
And the platform version you have is

Platform Version:				 OpenCL 2.1 AMD-APP (2527.8)

So if you added a strncmp line in

https://github.com/aparapi/aparapi/blob/master/com.amd.aparapi.jni/src/cpp/invoke/OpenCLJNI.cpp#L444

and rebuilt I think you would be good to .


Gary

**Comment by carstenhag** [comment]
Yeah, I've edited the file but I can't seem to compile `com.amd.aparapi.jni` at all.

Something seems to be seriously wrong on the jni project. `opencljni.cpp` is missing. I had to google the name and found a 6-year old commit where the file was submitted.

`com_amd_aparapi_OpenCLJNI.h` is missing.

I added 4-5 include folders to get to this point. I don't know what to do now. It's pretty frustrating that there is no BUILDING file or any instructions at all.
These are the header files that were generated (I have no clue of C/C++?):

![](https://i.imgur.com/ivVBc2N.png)

I tried to replace the `com_amd_aparapi_OpenCLJNI.h` include in opencljni.cpp by `com_amd_aparapi_internal_jni_OpenCLJNI` but that generated 100+ errors.

**Comment by rlamothe** [comment]
The Aparapi Java code needs to be compiled first, then the JNi code. Sorry your have trouble building, some folks do, some folks don’t, each environment can be slightly different. Are you seeing any errors with the Ant build?

**Comment by carstenhag** [comment]
aparapi ant build goes through and builds a jar, the jni one doesn't build much:

```
build.xml
OS Name:    Windows 10
OS Version: 10.0
OS Arch:    amd64
Java Ver:   1.8.0_121

      Note: Since AMD APP SDK 2.9 you can have multiple versions installed/co-exist on same machine, 
      so AMD introduced a completely new naming convention for their installation directories
      For example C:/Program Files/AMD APP SDK/2.9-1
   
init
amd.app.sdk.dir C:/Program Files (x86)/AMD APP SDK/3.0
 intel.app.sdk.dir ${intel.app.sdk.dir}
 freebsd.app.sdk.dir ${freebsd.app.sdk.dir}
 vendor.name amd
app.sdk.dir C:/Program Files (x86)/AMD APP SDK/3.0
 msvc.dir ${msvc.dir}
 msvc.sdk.dir ${msvc.sdk.dir}
check
clean
javah
Created dir: C:\Users\carstenh\Documents\git\aparapi\com.amd.aparapi.jni\include
msvc
gcc
gcc_mac
clang_freebsd
build

Ant build completed with 16 warnings in 1s at 03.02.2018 19:35
```

I'm pretty sure this is because the jni's `build.xml` only checks for Visual Studio 14 (2015) and not 2017 which I got installed:

```
      <available property="msvc.64.12.0.exists" file="C:/Program Files (x86)/Microsoft Visual Studio 14.0\VC\bin" type="dir"/>
      <condition property="msvc.dir" value="c:/Program Files (x86)/Microsoft Visual Studio 12.0">
         <and>
            <os family="windows" />
            <isset property="msvc.64.12.0.exists" />
            <not>
               <isset property="msvc.dir" />
            </not>
         </and>
      </condition>
```

I'm not sure what it wants to search for, or what path the msvc.dir property should point at, but the folder structures *seem* different.

It may be `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin` though.

**Comment by rlamothe** [comment]
Yes, the Ant script unfortunately does not auto-detect paths on Windows. Have you tried updating all of the 2015 paths to 2017 paths in the script to see if that works? I’m not sure why it would not work, but you never know. Also make sure to set the AMD paths as well. If it does not, let us know and we’ll try to help figure it out.

**Comment by carstenhag** [comment]
I've set up a VM and installed Visual Studio 2015 and the other tools on it.
Added the following lines to the build.xml under the msvc target.
```xml
        <arg value="/Ic:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\" />
        <arg value="/IC:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\um" />
        <arg value="/IC:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\shared" />
```
Without these, ant could not find windows.h, stdio.h and other files. I had to manually copy the `list` file to `list.h` so it could be found (I don't remember which folder that was in, sorry).

Opened in Visual Studio, it complains about `Cannot open source file: 'src\cpp\opencljni.cpp': No such 
file or directory` and `Cannot open source file: 'src\cpp\aparapi.cpp': No such file or directory`.

Ant begins compiling (after I added all those include paths), but the linker seems to fail:

```
[exec] c:\users\user\documents\git\aparapi\com.amd.aparapi.jni\src\cpp\Common.h(47): warning C4067: unexpected tokens following preprocessor directive - expected a newline
     [exec] agent.cpp
     [exec] Generating Code...
     [exec] LINK : fatal error LNK1104: cannot open file 'uuid.lib'
```

[Entire ant.log](https://github.com/aparapi/aparapi/files/1692286/ant.log)

Googling I found some people solving this by changing the project's linker settings, but doing so doesn't change what ant does, I believe. At least, removing `uuid.lib` from the linker's "Additional dependencies" doesn't work.

**Comment by carstenhag** [comment]
I seem to be progressing fixing up the Visual Studio project. It didn't find almost any (?) headers from inside the jni project, also, some .cpp files were in other folders than were VS expected them to be at.

**Comment by carstenhag** [comment]
I got it to compile via Visual Studio 2015. It built various files, including `aparapi_x86.dll`. Sadly I would like to have the x64 version of it.

I tried to create a new configuration (not sure if that was the name) in Visual Studio and chose x64.

The linker threw about 30 errors and there was some mismatch info being output. I will post the exact logs tomorrow.

Ant still doesn't build, keeps failing at the linker stage. Tried to pass some other parameters to it, but no dice.

**Comment by grfrost** [comment]
Yeah, sorry Carsten I switched from Windows as a dev environment a long
time ago.   Trying to track the directory changes between Visual Studio
releases was a pain in the neck as you can see from the 'scar tissue' in
the build.xml files.

I do recall that (at that time) you had to install  the 64 bit toolchain
separately.  I can't believe that this is still the case (can you buy 64
bit OS' any more?) but it may be.

One trick I learned was to create a small C++ lib project (64 bit) and then
dump the nmake file.

Other option is mingw.... But IMHO herein lies madness.

Gary
