### ISSUE TITLE
"no device object!" on 64bit Linux

### ISSUE THREAD

**Issue by jayjaybillings** [aparapi/aparapi#6]
I'm attempting to run the code below on 64bit Fedora 21. I have OpenCL 1.0. I have this code in a simple Java project in Eclipse with the Aparapi jar on the build path. My code compiles fine and so do the samples. I am using the 1.0.0 pre-release from the GitHub repo.

When I execute my code I receive the message "no device object!" and Java throws a SIGSEGV.

Running with -Dcom.amd.aparapi.enableVerboseJNI=true does not provide any extra information.

I'm primarily interested in running this code in JTP mode before trying out OpenCL mode (thus the big starting buffer size).

Any thoughts or suggestions would be appreciated!

Jay
-----

package org.jayjaybillings.math.prototypes;

import com.amd.aparapi.Kernel;

/**
 * Testing vector addition performance time.
 * 
 * @author Jay Jay Billings
 * 
 */
public class VecAddTest {

	/**
	 * @param args
	 */
	public static void main(String[] args) {

		final int num = 200000000, maxits = 1000;
		final float[] vec = new float[num];

		Kernel kernel = new Kernel() {
			@Override
			public void run() {
				for (int j = 0; j < maxits; j++) {
					for (int i = 0; i < num; i++) {
						vec[i] += i;
					}
				}
			}
		};
		kernel.execute(8);

		System.out.println(vec[1]);

	}

}

**Comment by SubaruWRC** [comment]
Do any of the examples run?


On April 3, 2015 8:05:17 PM PDT, Jay Jay Billings <notifications@github.com> wrote:
>I'm attempting to run the code below on 64bit Fedora 21. I have OpenCL
>1.0. I have this code in a simple Java project in Eclipse with the
>Aparapi jar on the build path. My code compiles fine and so do the
>samples. I am using the 1.0.0 pre-release from the GitHub repo.
>
>When I execute my code I receive the message "no device object!" and
>Java throws a SIGSEGV.
>
>Running with -Dcom.amd.aparapi.enableVerboseJNI=true does not provide
>any extra information.
>
>I'm primarily interested in running this code in JTP mode before trying
>out OpenCL mode (thus the big starting buffer size).
>
>Any thoughts or suggestions would be appreciated!
>
>Jay
>-----
>
>package org.jayjaybillings.math.prototypes;
>
>import com.amd.aparapi.Kernel;
>
>/**
> * Testing vector addition performance time.
> * 
> * @author Jay Jay Billings
> * 
> */
>public class VecAddTest {
>
>	/**
>	 * @param args
>	 */
>	public static void main(String[] args) {
>
>		final int num = 200000000, maxits = 1000;
>		final float[] vec = new float[num];
>
>		Kernel kernel = new Kernel() {
>			@Override
>			public void run() {
>				for (int j = 0; j < maxits; j++) {
>					for (int i = 0; i < num; i++) {
>						vec[i] += i;
>					}
>				}
>			}
>		};
>		kernel.execute(8);
>
>		System.out.println(vec[1]);
>
>	}
>
>}
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/aparapi/aparapi/issues/6

-- 
Sent from my mobile device. Please excuse any typos or autocorrect mistakes.

**Comment by jayjaybillings** [comment]
They all fail with the same message, "no device object!" except info. Info prints:

com.amd.aparapi.sample.info.Main
Machine contains 0 OpenCL platforms
OpenCLDevice.best() returned null!
OpenCLDevice.firstCPU() returned null!
OpenCLDevice.firstGPU() returned null!

I'm guessing that this means that my laptop does not have a valid OpenCL device. I'm running a G98M graphics card. I wouldn't think that would matter for running JTP mode though?

Jay

**Comment by SubaruWRC** [comment]
It shouldn't. There is a command-line switch (and code switch) to force Aparapi to JTP mode. I don't have it right now, but you can find it in all of the .bat and .sh files. Try that and see if it gives the same error.


On April 3, 2015 8:35:02 PM PDT, Jay Jay Billings <notifications@github.com> wrote:
>They all fail with the same message, "no device object!" except info.
>Info prints:
>
>com.amd.aparapi.sample.info.Main
>Machine contains 0 OpenCL platforms
>OpenCLDevice.best() returned null!
>OpenCLDevice.firstCPU() returned null!
>OpenCLDevice.firstGPU() returned null!
>
>I'm guessing that this means that my laptop does not have a valid
>OpenCL device. I'm running a G98M graphics card. I wouldn't think that
>would matter for running JTP mode though?
>
>Jay
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/aparapi/aparapi/issues/6#issuecomment-89493599

-- 
Sent from my mobile device. Please excuse any typos or autocorrect mistakes.

**Comment by jayjaybillings** [comment]
The examples work if I force JTP mode and my code works too with that
switch.

I wonder if this means I have a messed up OpenCL install?

**Comment by jayjaybillings** [comment]
I can confirm that this error does not appear on my other machine where I have an NVIDIA GTX 770. The G98M is on the list of supported cards at the Khronos Group's compliance site (listed as Quadro NVS 160M).

I'll close this bug for now since it seems to be a hardware specific thing for my laptop and isn't a problem on my other box.

Thanks very much for your help.

**Comment by SubaruWRC** [comment]
Yes, most likely. Make sure to use only official drivers from the manufacturer and verify that those drivers/hardware support OpenCL. If you are using an SDK, it will usually contain test apps to verify OpenCL is working.


On April 4, 2015 8:33:22 AM PDT, Jay Jay Billings <notifications@github.com> wrote:
>The examples work if I force JTP mode and my code works too with that
>switch.
>
>I wonder if this means I have a messed up OpenCL install?
>On Apr 4, 2015 11:11 AM, "SubaruWRC" <notifications@github.com> wrote:
>
>> It shouldn't. There is a command-line switch (and code switch) to
>force
>> Aparapi to JTP mode. I don't have it right now, but you can find it
>in all
>> of the .bat and .sh files. Try that and see if it gives the same
>error.
>>
>>
>> On April 3, 2015 8:35:02 PM PDT, Jay Jay Billings <
>> notifications@github.com> wrote:
>> >They all fail with the same message, "no device object!" except
>info.
>> >Info prints:
>> >
>> >com.amd.aparapi.sample.info.Main
>> >Machine contains 0 OpenCL platforms
>> >OpenCLDevice.best() returned null!
>> >OpenCLDevice.firstCPU() returned null!
>> >OpenCLDevice.firstGPU() returned null!
>> >
>> >I'm guessing that this means that my laptop does not have a valid
>> >OpenCL device. I'm running a G98M graphics card. I wouldn't think
>that
>> >would matter for running JTP mode though?
>> >
>> >Jay
>> >
>> >---
>> >Reply to this email directly or view it on GitHub:
>> >https://github.com/aparapi/aparapi/issues/6#issuecomment-89493599
>>
>> --
>> Sent from my mobile device. Please excuse any typos or autocorrect
>> mistakes.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/aparapi/aparapi/issues/6#issuecomment-89592803>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/aparapi/aparapi/issues/6#issuecomment-89598458

-- 
Sent from my mobile device. Please excuse any typos or autocorrect mistakes.

**Comment by SubaruWRC** [comment]
Any time, glad to help!


On April 4, 2015 2:01:33 PM PDT, Jay Jay Billings <notifications@github.com> wrote:
>I can confirm that this error does not appear on my other machine where
>I have an NVIDIA GTX 770. The G98M is on the list of supported cards at
>the Khronos Group's compliance site (listed as Quadro NVS 160M).
>
>I'll close this bug for now since it seems to be a hardware specific
>thing for my laptop and isn't a problem on my other box.
>
>Thanks very much for your help.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/aparapi/aparapi/issues/6#issuecomment-89667352

-- 
Sent from my mobile device. Please excuse any typos or autocorrect mistakes.
