### ISSUE TITLE
Port the wiki to markdowns inside doc dir

### ISSUE THREAD

**Issue by mibrahim** [aparapi/aparapi#9]
I started on this. Please let me know if there's another effort going on.

**Comment by mibrahim** [comment]
Do you care about the dates here:
https://github.com/mibrahim/aparapi/blob/master/doc/README.md
vs
https://code.google.com/p/aparapi/w/list

**Comment by grfrost** [comment]
I am sure we don't care about the dates.

Hey Mohammed, thanks for stepping up and doing this.

Gary

**Comment by mibrahim** [comment]
Noticed those as I was converting some documents yesterday. May be we can separate them as tickets in the future:
1. Some HSA youtube video links are broken
2. Converting bytecode to OpenCL has another PDF content attached. May be the PDF content should be copied back to the markdown text
